INSERT INTO EMPLOYEE VALUES(1, 'E1');
INSERT INTO EMPLOYEE VALUES(2, 'E2');

INSERT INTO PROJECT VALUES(1,'P1');
INSERT INTO PROJECT VALUES(2,'P2');

INSERT INTO DEPARTMENT VALUES(1,'D1');
INSERT INTO DEPARTMENT VALUES(2,'D2');

INSERT INTO EMP_PROJ_RELN values(1,1);
INSERT INTO EMP_PROJ_RELN values(1,2);
INSERT INTO EMP_PROJ_RELN values(2,1);
INSERT INTO EMP_PROJ_RELN values(2,2);

INSERT INTO EMP_DEPT_RELN values(1,1);
INSERT INTO EMP_DEPT_RELN values(1,2);
INSERT INTO EMP_DEPT_RELN values(2,1);
INSERT INTO EMP_DEPT_RELN values(2,2);

INSERT INTO DEPT_PROJ_RELN values(1,1);
INSERT INTO DEPT_PROJ_RELN values(1,2);
INSERT INTO DEPT_PROJ_RELN values(2,1);
INSERT INTO DEPT_PROJ_RELN values(2,2);